version: '3.7'

networks:
  outside:
    external: true

services:
  postgres:
    image: postgres:12.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=postgres
    networks:
      - default
      - outside
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  userservice:
    image: jacob-userservice:latest
    networks:
      - default
      - outside
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/postgres
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - postgres

volumes:
  postgres-data: